### ISSUE TITLE
NYC PD is over!

### ISSUE THREAD

**Issue by brianharvey** [beautyjoy/beautyjoy.github.io#59]
There's one more year of the grant, but it doesn't include PD, just writing up the research and wrapping up the curriculum.

**Comment by cycomachead** [comment]
So, next summer any teacher from NYC can attend regular PD / palooza / etc?

**Comment by brianharvey** [comment]
Oops, apparently there will be a NYC-funded new fourth cohort, but focusing on additional teachers from existing BJC schools for sustainability.  We're just hearing this at the monthly meeting.  So stay tuned...
