### ISSUE TITLE
updates needed to main BJC index.html page under 2018 PD section

### ISSUE THREAD

**Issue by tmbarnes** [beautyjoy/beautyjoy.github.io#66]
I made some direct edits to the main page on the server, but only at the bottom left on the info on summer PD. I've attached the index file as a txt file.

[bjc.berkeley.edu-index.html.txt](https://github.com/beautyjoy/beautyjoy.github.io/files/1549476/bjc.berkeley.edu-index.html.txt)

**Comment by cycomachead** [comment]
Fixed with 1f446f4a798a00c45fbbfb1c3515f9d06421c5a8
